"""Generate Sphinx wrapper pages for package-owned tool documentation."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import argparse
import os
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
PACKAGES_DIR = ROOT / "packages"
OUTPUT_DIR = ROOT / "docs" / "source" / "tool_packages"
FIRST_PARTY_ORDER = [
    "bioimageflow-common-tools",
    "bioimageflow-io-tools",
    "bioimageflow-segmentation-tools",
    "bioimageflow-measurement-tools",
    "bioimageflow-spot-tools",
    "bioimageflow-tracking-tools",
    "bioimageflow-restoration-tools",
    "bioimageflow-sairpico-tools",
]
GENERATED_HEADER = "<!-- Generated by docs/generate_tool_package_docs.py. Do not edit by hand. -->"
RAW_HTML_DOC_LINK_RE = re.compile(
    r"<a\s+[^>]*href=[\"']((?:tools|workflows)/[^\"']+\.md)[\"']",
    re.IGNORECASE,
)
MARKDOWN_DOC_LINK_RE = re.compile(
    r"(?<!!)\[[^\]]+\]\(((?:tools|workflows)/[^)\s#]+\.md)(?:#[^)]+)?\)"
)


@dataclass(frozen=True)
class PackageDocs:
    name: str
    title: str
    package_dir: Path
    docs_dir: Path
    index: Path
    tools: tuple[Path, ...]
    workflows: tuple[Path, ...]
    external_url: str | None = None

    @property
    def slug(self) -> str:
        return self.name


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated documentation wrappers are not up to date",
    )
    args = parser.parse_args()

    packages = discover_package_docs()
    link_errors = validate_package_doc_links(packages)
    if link_errors:
        print("Package documentation links are invalid:", file=sys.stderr)
        for error in link_errors:
            print(f"  {error}", file=sys.stderr)
        return 1

    pages = build_pages(packages)
    if args.check:
        return check_pages(pages)
    write_pages(pages)
    return 0


def discover_package_docs() -> list[PackageDocs]:
    packages = []
    seen = set()

    for name in FIRST_PARTY_ORDER:
        package_dir = PACKAGES_DIR / name
        docs = docs_from_package_dir(package_dir, first_party=True)
        if docs is not None:
            packages.append(docs)
            seen.add(docs.name)

    for package_dir in sorted(PACKAGES_DIR.glob("*")):
        if package_dir.name in seen:
            continue
        docs = docs_from_package_dir(package_dir, first_party=True)
        if docs is not None:
            packages.append(docs)
            seen.add(docs.name)

    for raw_path in os.environ.get("BIOIMAGEFLOW_DOC_PACKAGE_PATHS", "").split(os.pathsep):
        if not raw_path:
            continue
        docs = docs_from_package_dir(Path(raw_path), first_party=False)
        if docs is not None and docs.name not in seen:
            packages.append(docs)
            seen.add(docs.name)

    return packages


def docs_from_package_dir(package_dir: Path, *, first_party: bool) -> PackageDocs | None:
    pyproject = package_dir / "pyproject.toml"
    metadata = read_docs_metadata(pyproject)
    docs_root = metadata.get("root", "docs")
    index = metadata.get("index", f"{docs_root}/index.md")
    include = metadata.get("include_in_main_docs", first_party)
    external_url = metadata.get("documentation_url")

    if not include and not external_url:
        return None

    docs_dir = package_dir / str(docs_root)
    index_path = package_dir / str(index)
    if not index_path.exists():
        if external_url:
            title = str(metadata.get("title") or package_dir.name)
            return PackageDocs(
                name=package_dir.name,
                title=title,
                package_dir=package_dir,
                docs_dir=docs_dir,
                index=index_path,
                tools=(),
                workflows=(),
                external_url=str(external_url),
            )
        return None

    return PackageDocs(
        name=package_dir.name,
        title=str(metadata.get("title") or markdown_title(index_path) or package_dir.name),
        package_dir=package_dir,
        docs_dir=docs_dir,
        index=index_path,
        tools=markdown_pages(docs_dir / "tools"),
        workflows=markdown_pages(docs_dir / "workflows"),
        external_url=str(external_url) if external_url else None,
    )


def read_docs_metadata(pyproject: Path) -> dict[str, object]:
    if not pyproject.exists():
        return {}

    text = pyproject.read_text()
    match = re.search(r"(?ms)^\[tool\.bioimageflow\.docs\]\s*(.*?)(?=^\[|\Z)", text)
    if match is None:
        return {}

    metadata: dict[str, object] = {}
    for line in match.group(1).splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or "=" not in line:
            continue
        key, value = [part.strip() for part in line.split("=", 1)]
        metadata[key] = parse_toml_scalar(value)
    return metadata


def parse_toml_scalar(value: str) -> object:
    if value in {"true", "false"}:
        return value == "true"
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return value[1:-1]
    if re.fullmatch(r"\d+", value):
        return int(value)
    return value


def markdown_pages(directory: Path) -> tuple[Path, ...]:
    if not directory.exists():
        return ()
    return tuple(
        path
        for path in sorted(directory.glob("*.md"))
        if path.name.lower() != "readme.md"
    )


def markdown_title(path: Path) -> str | None:
    for line in path.read_text().splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def validate_package_doc_links(packages: list[PackageDocs]) -> list[str]:
    errors = []
    for package in packages:
        if package.external_url or not package.index.exists():
            continue

        text = package.index.read_text()
        for href in RAW_HTML_DOC_LINK_RE.findall(text):
            errors.append(
                f"{package.index.relative_to(ROOT)} links to {href} with raw HTML; "
                "use a Markdown link so Sphinx can rewrite it"
            )
        for href in MARKDOWN_DOC_LINK_RE.findall(text):
            target = package.docs_dir / href
            if not target.exists():
                errors.append(
                    f"{package.index.relative_to(ROOT)} links to missing package doc page {href}"
                )
    return errors


def build_pages(packages: list[PackageDocs]) -> dict[Path, str]:
    pages: dict[Path, str] = {}
    pages[OUTPUT_DIR / "index.md"] = tool_packages_index(packages)

    for package in packages:
        if package.external_url:
            continue
        package_dir = OUTPUT_DIR / package.slug
        pages[package_dir / "index.md"] = package_index(package)
        for page in package.tools:
            pages[package_dir / "tools" / page.name] = include_page(page)
        for page in package.workflows:
            pages[package_dir / "workflows" / page.name] = include_page(page)

    return pages


def tool_packages_index(packages: list[PackageDocs]) -> str:
    local_packages = [package for package in packages if not package.external_url]
    external_packages = [package for package in packages if package.external_url]
    package_links = "\n".join(
        f"- [{package.title}]({package.slug}/index.md)" for package in local_packages
    )
    external = ""
    if external_packages:
        links = "\n".join(
            f"- [{package.title}]({package.external_url})" for package in external_packages
        )
        external = f"\n## External Package Docs\n\n{links}\n"

    return f"""{GENERATED_HEADER}

# Tool Packages

BioImageFlow tool package documentation is included from package-owned `docs/` directories.
Each package owns its tools, workflows, tests, examples, and detailed user documentation.

Custom package docs can be added to a local documentation build by setting `BIOIMAGEFLOW_DOC_PACKAGE_PATHS` to one or more package directories that declare `[tool.bioimageflow.docs]` metadata.

## First-Party Packages

{package_links}
{external}"""


def package_index(package: PackageDocs) -> str:
    include = include_directive(package.index, wrapper=OUTPUT_DIR / package.slug / "index.md")
    entries = []
    entries.extend(f"tools/{page.stem}" for page in package.tools)
    entries.extend(f"workflows/{page.stem}" for page in package.workflows)
    toctree = ""
    if entries:
        toctree = "\n## Detailed Pages\n\n```{toctree}\n:maxdepth: 1\n\n" + "\n".join(entries) + "\n```\n"
    return f"{GENERATED_HEADER}\n\n{include}\n{toctree}"


def include_page(source: Path) -> str:
    return f"{GENERATED_HEADER}\n\n{include_directive(source)}"


def include_directive(source: Path, *, wrapper: Path | None = None) -> str:
    wrapper_path = wrapper or generated_wrapper_for_source(source)
    relative_source = relative_posix(source, wrapper_path.parent)
    relative_docs = relative_posix(source.parent, wrapper_path.parent)
    return f"""```{{include}} {relative_source}
:relative-docs: {relative_docs}/
```
"""


def generated_wrapper_for_source(source: Path) -> Path:
    package_dir = next(parent for parent in source.parents if parent.parent == PACKAGES_DIR)
    relative = source.relative_to(package_dir / "docs")
    return OUTPUT_DIR / package_dir.name / relative


def relative_posix(path: Path, start: Path) -> str:
    return os.path.relpath(path, start).replace(os.sep, "/")


def write_pages(pages: dict[Path, str]) -> None:
    for path, content in pages.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def check_pages(pages: dict[Path, str]) -> int:
    stale = []
    for path, content in pages.items():
        if not path.exists() or path.read_text() != content:
            stale.append(str(path.relative_to(ROOT)))

    if stale:
        print("Generated tool package docs are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run: uv run python docs/generate_tool_package_docs.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
